#!/bin/sh

testfile=tests
if [ $# -ge 1 ]; then testfile=$1; fi

basedir=`head -n 1 $testfile | awk '{print $2}'`
basedir=`cd $basedir;pwd`
dirs=`awk -F '#' '{print $1}' $testfile`

for dir in $dirs; do
    echo $dir
    ../src/ac3dec $basedir/$dir/stream >/dev/null 2>&1
    ./compare output.pcm $basedir/$dir/output.pcm
    rm -f output.pcm
done
