#!/bin/sh

if test x"$srcdir" = x""; then srcdir="."; fi

testfile=$srcdir/tests
if [ $# -ge 1 ]; then testfile=$1; fi

basedir=`head -n 1 $testfile | awk '{print $2}'`
home=`pwd`; cd $srcdir; if [ ! -d $basedir ]; then exit 77; else cd $home; fi

dirs=`awk -F '#' '{print $1}' $testfile`

for dir in $dirs; do
    echo $dir
    ../src/ac3dec $basedir/$dir/stream >/dev/null 2>&1
    ./compare output.pcm $basedir/$dir/output.pcm
    rm -f output.pcm
done
